name: Packer Checks

# Trigger workflow on pull request creation or updates
on:
  pull_request:
    branches:
      - main

jobs:
  packer_checks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Packer
      - name: Set up Packer
        run: |
          curl -LO "https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip" # Update version as necessary
          unzip packer_1.8.0_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          rm packer_1.8.0_linux_amd64.zip

      # Step 3: Run Packer Format
      - name: Run Packer fmt
        id: packer_fmt
        run: |
          if ! packer fmt -check packer_template.json; then
            echo "Packer template is not formatted correctly."
            exit 1
          fi

      # Step 4: Run Packer Validate
      - name: Run Packer validate
        run: |
          if ! packer validate packer_template.json; then
            echo "Packer template is not valid."
            exit 1
          fi